// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========

// Generated by scripts/gen_tz_abbrevs.py; do not edit by hand.
//
// The abbreviations every tzdata zone has carried since 1970: one row per
// name an offset has shown, `[offset in seconds east, name, the epoch
// second it took effect]`, in the order the names took effect, with 0 for
// the rows in effect at 1970. This is what GNU date prints for `%Z` and
// what Python's zoneinfo renders; Intl only offers `GMT+8`, so the
// TypeScript `date` looks the name up here by the offset Intl does report
// and the instant rendered (tzAbbreviation). An offset tzdata only ever
// spelled out (`+08`, `-03`) has no row and renders that way; one that
// carried letters at some time keeps every name it carried, so Moscow's
// +04 reads MSD before 2011 and MSK after, and Istanbul's +03 reads EEST
// in the summers before 2016 and +03 since.

// One name an offset carried: offset in seconds east, the name, the epoch
// second it took effect.
type Abbreviation = readonly [number, string, number]

export const TZ_ABBREVS: Readonly<Record<string, readonly Abbreviation[]>> = {
  'Africa/Abidjan': [[0, 'GMT', 0]],
  'Africa/Accra': [[0, 'GMT', 0]],
  'Africa/Addis_Ababa': [[10800, 'EAT', 0]],
  'Africa/Algiers': [
    [0, 'WET', 0],
    [3600, 'WEST', 41468400],
    [3600, 'CET', 246236400],
    [7200, 'CEST', 259545600],
    [3600, 'WEST', 325468800],
    [3600, 'CET', 357523200],
  ],
  'Africa/Asmara': [[10800, 'EAT', 0]],
  'Africa/Asmera': [[10800, 'EAT', 0]],
  'Africa/Bamako': [[0, 'GMT', 0]],
  'Africa/Bangui': [[3600, 'WAT', 0]],
  'Africa/Banjul': [[0, 'GMT', 0]],
  'Africa/Bissau': [[0, 'GMT', 157770000]],
  'Africa/Blantyre': [[7200, 'CAT', 0]],
  'Africa/Brazzaville': [[3600, 'WAT', 0]],
  'Africa/Bujumbura': [[7200, 'CAT', 0]],
  'Africa/Cairo': [
    [7200, 'EET', 0],
    [10800, 'EEST', 10364400],
  ],
  'Africa/Ceuta': [
    [0, 'WET', 0],
    [3600, 'WEST', 141264000],
    [3600, 'CET', 448243200],
    [7200, 'CEST', 512528400],
  ],
  'Africa/Conakry': [[0, 'GMT', 0]],
  'Africa/Dakar': [[0, 'GMT', 0]],
  'Africa/Dar_es_Salaam': [[10800, 'EAT', 0]],
  'Africa/Djibouti': [[10800, 'EAT', 0]],
  'Africa/Douala': [[3600, 'WAT', 0]],
  'Africa/Freetown': [[0, 'GMT', 0]],
  'Africa/Gaborone': [[7200, 'CAT', 0]],
  'Africa/Harare': [[7200, 'CAT', 0]],
  'Africa/Johannesburg': [[7200, 'SAST', 0]],
  'Africa/Juba': [
    [7200, 'CAT', 0],
    [10800, 'CAST', 10360800],
    [10800, 'EAT', 947930400],
  ],
  'Africa/Kampala': [[10800, 'EAT', 0]],
  'Africa/Khartoum': [
    [7200, 'CAT', 0],
    [10800, 'CAST', 10360800],
    [10800, 'EAT', 947930400],
  ],
  'Africa/Kigali': [[7200, 'CAT', 0]],
  'Africa/Kinshasa': [[3600, 'WAT', 0]],
  'Africa/Lagos': [[3600, 'WAT', 0]],
  'Africa/Libreville': [[3600, 'WAT', 0]],
  'Africa/Lome': [[0, 'GMT', 0]],
  'Africa/Luanda': [[3600, 'WAT', 0]],
  'Africa/Lubumbashi': [[7200, 'CAT', 0]],
  'Africa/Lusaka': [[7200, 'CAT', 0]],
  'Africa/Malabo': [[3600, 'WAT', 0]],
  'Africa/Maputo': [[7200, 'CAT', 0]],
  'Africa/Maseru': [[7200, 'SAST', 0]],
  'Africa/Mbabane': [[7200, 'SAST', 0]],
  'Africa/Mogadishu': [[10800, 'EAT', 0]],
  'Africa/Monrovia': [
    [-2670, 'MMT', 0],
    [0, 'GMT', 63593070],
  ],
  'Africa/Nairobi': [[10800, 'EAT', 0]],
  'Africa/Ndjamena': [
    [3600, 'WAT', 0],
    [7200, 'WAST', 308703600],
  ],
  'Africa/Niamey': [[3600, 'WAT', 0]],
  'Africa/Nouakchott': [[0, 'GMT', 0]],
  'Africa/Ouagadougou': [[0, 'GMT', 0]],
  'Africa/Porto-Novo': [[3600, 'WAT', 0]],
  'Africa/Sao_Tome': [
    [0, 'GMT', 0],
    [3600, 'WAT', 1514768400],
  ],
  'Africa/Timbuktu': [[0, 'GMT', 0]],
  'Africa/Tripoli': [
    [7200, 'EET', 0],
    [3600, 'CET', 378684000],
    [7200, 'CEST', 386463600],
    [7200, 'EET', 641775600],
    [7200, 'CEST', 860108400],
    [7200, 'EET', 875916000],
    [7200, 'CEST', 1364515200],
    [7200, 'EET', 1382659200],
  ],
  'Africa/Tunis': [
    [3600, 'CET', 0],
    [7200, 'CEST', 231202800],
  ],
  'Africa/Windhoek': [
    [7200, 'SAST', 0],
    [7200, 'CAT', 637970400],
    [3600, 'WAT', 764200800],
  ],
  'America/Adak': [
    [-39600, 'BST', 0],
    [-36000, 'BDT', 9982800],
    [-36000, 'AHST', 436363200],
    [-36000, 'HST', 439034400],
    [-32400, 'HDT', 452088000],
  ],
  'America/Anchorage': [
    [-36000, 'AHST', 0],
    [-32400, 'AHDT', 9979200],
    [-32400, 'YST', 436359600],
    [-32400, 'AKST', 439030800],
    [-28800, 'AKDT', 452084400],
  ],
  'America/Anguilla': [[-14400, 'AST', 0]],
  'America/Antigua': [[-14400, 'AST', 0]],
  'America/Aruba': [[-14400, 'AST', 0]],
  'America/Atikokan': [[-18000, 'EST', 0]],
  'America/Atka': [
    [-39600, 'BST', 0],
    [-36000, 'BDT', 9982800],
    [-36000, 'AHST', 436363200],
    [-36000, 'HST', 439034400],
    [-32400, 'HDT', 452088000],
  ],
  'America/Bahia_Banderas': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 828867600],
    [-18000, 'CDT', 1270371600],
    [-21600, 'CST', 1288508400],
  ],
  'America/Barbados': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 234943200],
  ],
  'America/Belize': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 123919200],
  ],
  'America/Blanc-Sablon': [[-14400, 'AST', 0]],
  'America/Boise': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
  ],
  'America/Cambridge_Bay': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 73472400],
    [-21600, 'CST', 941356800],
    [-18000, 'CDT', 954662400],
    [-18000, 'EST', 972802800],
    [-21600, 'MDT', 986115600],
  ],
  'America/Cancun': [
    [-21600, 'CST', 0],
    [-18000, 'EST', 378201600],
    [-18000, 'CDT', 828864000],
    [-18000, 'EST', 877849200],
    [-14400, 'EDT', 891759600],
    [-18000, 'CDT', 902037600],
    [-18000, 'EST', 1422777600],
  ],
  'America/Cayman': [[-18000, 'EST', 0]],
  'America/Chicago': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
  ],
  'America/Chihuahua': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 828864000],
    [-21600, 'MDT', 891766800],
    [-25200, 'MST', 909302400],
    [-21600, 'CST', 1667116800],
  ],
  'America/Ciudad_Juarez': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 828864000],
    [-21600, 'MDT', 891766800],
    [-25200, 'MST', 909302400],
    [-21600, 'CST', 1667116800],
    [-21600, 'MDT', 1678611600],
  ],
  'America/Coral_Harbour': [[-18000, 'EST', 0]],
  'America/Costa_Rica': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 288770400],
  ],
  'America/Creston': [[-25200, 'MST', 0]],
  'America/Curacao': [[-14400, 'AST', 0]],
  'America/Danmarkshavn': [[0, 'GMT', 820465200]],
  'America/Dawson': [
    [-32400, 'YST', 0],
    [-28800, 'PST', 120646800],
    [-25200, 'PDT', 325677600],
    [-25200, 'MST', 1604214000],
  ],
  'America/Dawson_Creek': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
    [-25200, 'MST', 84013200],
  ],
  'America/Denver': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
  ],
  'America/Detroit': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 104914800],
  ],
  'America/Dominica': [[-14400, 'AST', 0]],
  'America/Edmonton': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 73472400],
    [-21600, 'CST', 1793520000],
  ],
  'America/El_Salvador': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 547020000],
  ],
  'America/Ensenada': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
  ],
  'America/Fort_Nelson': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
    [-25200, 'MST', 1425808800],
  ],
  'America/Fort_Wayne': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Glace_Bay': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 73461600],
  ],
  'America/Goose_Bay': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 9957600],
    [-7200, 'ADDT', 576043260],
  ],
  'America/Grand_Turk': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 294217200],
    [-14400, 'AST', 1425798000],
    [-14400, 'EDT', 1520751600],
  ],
  'America/Grenada': [[-14400, 'AST', 0]],
  'America/Guadeloupe': [[-14400, 'AST', 0]],
  'America/Guatemala': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 123055200],
  ],
  'America/Halifax': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 9957600],
  ],
  'America/Havana': [
    [-18000, 'CST', 0],
    [-14400, 'CDT', 9954000],
  ],
  'America/Hermosillo': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 828867600],
  ],
  'America/Indiana/Indianapolis': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Indiana/Knox': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
    [-18000, 'EST', 688546800],
    [-18000, 'CDT', 1143961200],
  ],
  'America/Indiana/Marengo': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
    [-18000, 'CDT', 126687600],
    [-18000, 'EST', 152089200],
  ],
  'America/Indiana/Petersburg': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
    [-18000, 'EST', 247042800],
    [-18000, 'CDT', 1143961200],
    [-18000, 'EST', 1194159600],
    [-14400, 'EDT', 1205046000],
  ],
  'America/Indiana/Tell_City': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
    [-18000, 'CDT', 1143961200],
    [-21600, 'CST', 1162105200],
  ],
  'America/Indiana/Vevay': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Indiana/Vincennes': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
    [-18000, 'CDT', 1143961200],
    [-21600, 'CST', 1162105200],
    [-18000, 'EST', 1194159600],
  ],
  'America/Indiana/Winamac': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
    [-18000, 'CDT', 1143961200],
    [-21600, 'CST', 1162105200],
    [-18000, 'EST', 1194156000],
  ],
  'America/Indianapolis': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Inuvik': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 73476000],
    [-21600, 'MDT', 294228000],
    [-25200, 'MST', 309945600],
  ],
  'America/Iqaluit': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 73465200],
    [-21600, 'CST', 941349600],
    [-18000, 'CDT', 954662400],
    [-18000, 'EST', 972802800],
  ],
  'America/Jamaica': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 126687600],
  ],
  'America/Juneau': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
    [-28800, 'YDT', 325677600],
    [-28800, 'PST', 341402400],
    [-32400, 'YST', 436352400],
    [-32400, 'AKST', 439030800],
    [-28800, 'AKDT', 452084400],
  ],
  'America/Kentucky/Louisville': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
    [-18000, 'CDT', 126687600],
    [-18000, 'EST', 152089200],
  ],
  'America/Kentucky/Monticello': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
    [-18000, 'EST', 972802800],
    [-14400, 'EDT', 986108400],
  ],
  'America/Knox_IN': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
    [-18000, 'EST', 688546800],
    [-18000, 'CDT', 1143961200],
  ],
  'America/Kralendijk': [[-14400, 'AST', 0]],
  'America/Los_Angeles': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
  ],
  'America/Louisville': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
    [-18000, 'CDT', 126687600],
    [-18000, 'EST', 152089200],
  ],
  'America/Lower_Princes': [[-14400, 'AST', 0]],
  'America/Managua': [
    [-21600, 'CST', 0],
    [-18000, 'EST', 105084000],
    [-18000, 'CDT', 290584800],
    [-18000, 'EST', 694260000],
    [-18000, 'CDT', 1113112800],
  ],
  'America/Marigot': [[-14400, 'AST', 0]],
  'America/Martinique': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 323841600],
  ],
  'America/Matamoros': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 576057600],
  ],
  'America/Mazatlan': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 828867600],
  ],
  'America/Menominee': [
    [-18000, 'EST', 0],
    [-18000, 'CDT', 104914800],
    [-21600, 'CST', 120639600],
  ],
  'America/Merida': [
    [-21600, 'CST', 0],
    [-18000, 'EST', 378201600],
    [-18000, 'CDT', 828864000],
  ],
  'America/Metlakatla': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
    [-32400, 'AKST', 1446372000],
    [-28800, 'AKDT', 1457866800],
    [-28800, 'PST', 1541325600],
    [-28800, 'AKDT', 1552215600],
  ],
  'America/Mexico_City': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 828864000],
  ],
  'America/Miquelon': [[-14400, 'AST', 0]],
  'America/Moncton': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 9957600],
  ],
  'America/Monterrey': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 576057600],
  ],
  'America/Montreal': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Montserrat': [[-14400, 'AST', 0]],
  'America/Nassau': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/New_York': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Nipigon': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Nome': [
    [-39600, 'BST', 0],
    [-36000, 'BDT', 9982800],
    [-32400, 'YST', 436363200],
    [-32400, 'AKST', 439030800],
    [-28800, 'AKDT', 452084400],
  ],
  'America/North_Dakota/Beulah': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
    [-21600, 'CST', 1289116800],
    [-18000, 'CDT', 1300003200],
  ],
  'America/North_Dakota/Center': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
    [-21600, 'CST', 720000000],
    [-18000, 'CDT', 733910400],
  ],
  'America/North_Dakota/New_Salem': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
    [-21600, 'CST', 1067155200],
    [-18000, 'CDT', 1081065600],
  ],
  'America/Ojinaga': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 828864000],
    [-21600, 'MDT', 891766800],
    [-25200, 'MST', 909302400],
    [-21600, 'CST', 1667116800],
  ],
  'America/Panama': [[-18000, 'EST', 0]],
  'America/Pangnirtung': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 73465200],
    [-21600, 'CST', 941349600],
    [-18000, 'CDT', 954662400],
    [-18000, 'EST', 972802800],
  ],
  'America/Phoenix': [[-25200, 'MST', 0]],
  'America/Port-au-Prince': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 421218000],
  ],
  'America/Port_of_Spain': [[-14400, 'AST', 0]],
  'America/Puerto_Rico': [[-14400, 'AST', 0]],
  'America/Rainy_River': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
  ],
  'America/Rankin_Inlet': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 73468800],
    [-18000, 'EST', 972802800],
    [-18000, 'CDT', 986112000],
  ],
  'America/Regina': [[-21600, 'CST', 0]],
  'America/Resolute': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 73468800],
    [-18000, 'EST', 972802800],
    [-18000, 'CDT', 986112000],
    [-18000, 'EST', 1162105200],
    [-18000, 'CDT', 1173600000],
  ],
  'America/Santa_Isabel': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
  ],
  'America/Santo_Domingo': [
    [-18000, 'EST', 4422600],
    [-14400, 'AST', 152082000],
  ],
  'America/Shiprock': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
  ],
  'America/Sitka': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
    [-32400, 'YST', 436352400],
    [-32400, 'AKST', 439030800],
    [-28800, 'AKDT', 452084400],
  ],
  'America/St_Barthelemy': [[-14400, 'AST', 0]],
  'America/St_Johns': [
    [-12600, 'NST', 0],
    [-9000, 'NDT', 9955800],
    [-5400, 'NDDT', 576041460],
  ],
  'America/St_Kitts': [[-14400, 'AST', 0]],
  'America/St_Lucia': [[-14400, 'AST', 0]],
  'America/St_Thomas': [[-14400, 'AST', 0]],
  'America/St_Vincent': [[-14400, 'AST', 0]],
  'America/Swift_Current': [
    [-25200, 'MST', 0],
    [-21600, 'CST', 73472400],
  ],
  'America/Tegucigalpa': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 547020000],
  ],
  'America/Thule': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 670399200],
  ],
  'America/Thunder_Bay': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Tijuana': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
  ],
  'America/Toronto': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'America/Tortola': [[-14400, 'AST', 0]],
  'America/Vancouver': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
    [-25200, 'MST', 1793523600],
  ],
  'America/Virgin': [[-14400, 'AST', 0]],
  'America/Whitehorse': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 325677600],
    [-25200, 'MST', 1604214000],
  ],
  'America/Winnipeg': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
  ],
  'America/Yakutat': [
    [-32400, 'YST', 0],
    [-28800, 'YDT', 9975600],
    [-32400, 'AKST', 439030800],
    [-28800, 'AKDT', 452084400],
  ],
  'America/Yellowknife': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 73472400],
    [-21600, 'CST', 1793520000],
  ],
  'Antarctica/Macquarie': [
    [39600, 'AEDT', 0],
    [36000, 'AEST', 5673600],
  ],
  'Antarctica/McMurdo': [
    [43200, 'NZST', 0],
    [46800, 'NZDT', 152632800],
  ],
  'Antarctica/Rothera': [[0, '-00', 0]],
  'Antarctica/South_Pole': [
    [43200, 'NZST', 0],
    [46800, 'NZDT', 152632800],
  ],
  'Antarctica/Troll': [
    [0, '-00', 0],
    [0, '+00', 1108166400],
  ],
  'Antarctica/Vostok': [[0, '-00', 760035600]],
  'Arctic/Longyearbyen': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323830800],
  ],
  'Asia/Amman': [
    [7200, 'EET', 0],
    [10800, 'EEST', 108165600],
    [10800, '+03', 1666908000],
  ],
  'Asia/Beirut': [
    [7200, 'EET', 0],
    [10800, 'EEST', 78012000],
  ],
  'Asia/Calcutta': [[19800, 'IST', 0]],
  'Asia/Chongqing': [
    [28800, 'CST', 0],
    [32400, 'CDT', 515527200],
  ],
  'Asia/Chungking': [
    [28800, 'CST', 0],
    [32400, 'CDT', 515527200],
  ],
  'Asia/Damascus': [
    [7200, 'EET', 0],
    [10800, 'EEST', 10368000],
    [10800, '+03', 1666904400],
  ],
  'Asia/Famagusta': [
    [7200, 'EET', 0],
    [10800, 'EEST', 166572000],
    [10800, '+03', 1473282000],
    [10800, 'EEST', 1521939600],
  ],
  'Asia/Gaza': [
    [7200, 'IST', 0],
    [10800, 'IDT', 142380000],
    [7200, 'EET', 820447200],
    [10800, 'EEST', 828655200],
  ],
  'Asia/Harbin': [
    [28800, 'CST', 0],
    [32400, 'CDT', 515527200],
  ],
  'Asia/Hebron': [
    [7200, 'IST', 0],
    [10800, 'IDT', 142380000],
    [7200, 'EET', 820447200],
    [10800, 'EEST', 828655200],
  ],
  'Asia/Hong_Kong': [
    [28800, 'HKT', 0],
    [32400, 'HKST', 9315000],
  ],
  'Asia/Istanbul': [
    [7200, 'EET', 0],
    [10800, 'EEST', 107910000],
    [10800, '+03', 267915600],
    [10800, 'EEST', 482799600],
    [10800, '+03', 1473195600],
  ],
  'Asia/Jakarta': [[25200, 'WIB', 0]],
  'Asia/Jayapura': [[32400, 'WIT', 0]],
  'Asia/Jerusalem': [
    [7200, 'IST', 0],
    [10800, 'IDT', 142380000],
  ],
  'Asia/Karachi': [
    [18000, '+05', 0],
    [18000, 'PKT', 38775600],
    [21600, 'PKST', 1018119600],
  ],
  'Asia/Kolkata': [[19800, 'IST', 0]],
  'Asia/Macao': [
    [28800, 'CST', 0],
    [32400, 'CDT', 9315000],
  ],
  'Asia/Macau': [
    [28800, 'CST', 0],
    [32400, 'CDT', 9315000],
  ],
  'Asia/Makassar': [[28800, 'WITA', 0]],
  'Asia/Manila': [
    [28800, 'PST', 0],
    [32400, 'PDT', 228326400],
  ],
  'Asia/Nicosia': [
    [7200, 'EET', 0],
    [10800, 'EEST', 166572000],
  ],
  'Asia/Pontianak': [
    [28800, 'WITA', 0],
    [25200, 'WIB', 567964800],
  ],
  'Asia/Pyongyang': [
    [32400, 'KST', 0],
    [30600, 'KST', 1439564400],
  ],
  'Asia/Seoul': [
    [32400, 'KST', 0],
    [36000, 'KDT', 547578000],
  ],
  'Asia/Shanghai': [
    [28800, 'CST', 0],
    [32400, 'CDT', 515527200],
  ],
  'Asia/Taipei': [
    [28800, 'CST', 0],
    [32400, 'CDT', 133977600],
  ],
  'Asia/Tel_Aviv': [
    [7200, 'IST', 0],
    [10800, 'IDT', 142380000],
  ],
  'Asia/Tokyo': [[32400, 'JST', 0]],
  'Asia/Ujung_Pandang': [[28800, 'WITA', 0]],
  'Atlantic/Azores': [
    [0, '+00', 386125200],
    [0, 'WET', 725421600],
    [3600, 'WEST', 733280400],
    [0, '+00', 740278800],
  ],
  'Atlantic/Bermuda': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 136360800],
  ],
  'Atlantic/Canary': [
    [0, 'WET', 0],
    [3600, 'WEST', 323827200],
  ],
  'Atlantic/Faeroe': [
    [0, 'WET', 0],
    [3600, 'WEST', 354675600],
  ],
  'Atlantic/Faroe': [
    [0, 'WET', 0],
    [3600, 'WEST', 354675600],
  ],
  'Atlantic/Jan_Mayen': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323830800],
  ],
  'Atlantic/Madeira': [
    [0, 'WET', 0],
    [3600, 'WEST', 386726400],
  ],
  'Atlantic/Reykjavik': [[0, 'GMT', 0]],
  'Atlantic/St_Helena': [[0, 'GMT', 0]],
  'Australia/ACT': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/Adelaide': [
    [34200, 'ACST', 0],
    [37800, 'ACDT', 57688200],
  ],
  'Australia/Brisbane': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/Broken_Hill': [
    [34200, 'ACST', 0],
    [37800, 'ACDT', 57688200],
  ],
  'Australia/Canberra': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/Currie': [
    [39600, 'AEDT', 0],
    [36000, 'AEST', 5673600],
  ],
  'Australia/Darwin': [[34200, 'ACST', 0]],
  'Australia/Hobart': [
    [39600, 'AEDT', 0],
    [36000, 'AEST', 5673600],
  ],
  'Australia/LHI': [[36000, 'AEST', 0]],
  'Australia/Lindeman': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/Lord_Howe': [[36000, 'AEST', 0]],
  'Australia/Melbourne': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/NSW': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/North': [[34200, 'ACST', 0]],
  'Australia/Perth': [
    [28800, 'AWST', 0],
    [32400, 'AWDT', 152042400],
  ],
  'Australia/Queensland': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/South': [
    [34200, 'ACST', 0],
    [37800, 'ACDT', 57688200],
  ],
  'Australia/Sydney': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/Tasmania': [
    [39600, 'AEDT', 0],
    [36000, 'AEST', 5673600],
  ],
  'Australia/Victoria': [
    [36000, 'AEST', 0],
    [39600, 'AEDT', 57686400],
  ],
  'Australia/West': [
    [28800, 'AWST', 0],
    [32400, 'AWDT', 152042400],
  ],
  'Australia/Yancowinna': [
    [34200, 'ACST', 0],
    [37800, 'ACDT', 57688200],
  ],
  CET: [
    [3600, 'CET', 0],
    [7200, 'CEST', 228877200],
  ],
  CST6CDT: [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
  ],
  'Canada/Atlantic': [
    [-14400, 'AST', 0],
    [-10800, 'ADT', 9957600],
  ],
  'Canada/Central': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
  ],
  'Canada/Eastern': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'Canada/Mountain': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 73472400],
    [-21600, 'CST', 1793520000],
  ],
  'Canada/Newfoundland': [
    [-12600, 'NST', 0],
    [-9000, 'NDT', 9955800],
    [-5400, 'NDDT', 576041460],
  ],
  'Canada/Pacific': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
    [-25200, 'MST', 1793523600],
  ],
  'Canada/Saskatchewan': [[-21600, 'CST', 0]],
  'Canada/Yukon': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 325677600],
    [-25200, 'MST', 1604214000],
  ],
  Cuba: [
    [-18000, 'CST', 0],
    [-14400, 'CDT', 9954000],
  ],
  EET: [
    [7200, 'EET', 0],
    [10800, 'EEST', 166485600],
  ],
  EST: [[-18000, 'EST', 0]],
  EST5EDT: [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  Egypt: [
    [7200, 'EET', 0],
    [10800, 'EEST', 10364400],
  ],
  Eire: [
    [3600, 'IST', 0],
    [0, 'GMT', 57722400],
  ],
  'Etc/GMT': [[0, 'GMT', 0]],
  'Etc/GMT+0': [[0, 'GMT', 0]],
  'Etc/GMT-0': [[0, 'GMT', 0]],
  'Etc/GMT0': [[0, 'GMT', 0]],
  'Etc/Greenwich': [[0, 'GMT', 0]],
  'Etc/UCT': [[0, 'UTC', 0]],
  'Etc/UTC': [[0, 'UTC', 0]],
  'Etc/Universal': [[0, 'UTC', 0]],
  'Etc/Zulu': [[0, 'UTC', 0]],
  'Europe/Amsterdam': [
    [3600, 'CET', 0],
    [7200, 'CEST', 228877200],
  ],
  'Europe/Andorra': [
    [3600, 'CET', 0],
    [7200, 'CEST', 481078800],
  ],
  'Europe/Athens': [
    [7200, 'EET', 0],
    [10800, 'EEST', 166485600],
  ],
  'Europe/Belfast': [
    [3600, 'BST', 0],
    [0, 'GMT', 57722400],
  ],
  'Europe/Belgrade': [
    [3600, 'CET', 0],
    [7200, 'CEST', 417574800],
  ],
  'Europe/Berlin': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323830800],
  ],
  'Europe/Bratislava': [
    [3600, 'CET', 0],
    [7200, 'CEST', 291776400],
  ],
  'Europe/Brussels': [
    [3600, 'CET', 0],
    [7200, 'CEST', 228877200],
  ],
  'Europe/Bucharest': [
    [7200, 'EET', 0],
    [10800, 'EEST', 296604000],
  ],
  'Europe/Budapest': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323823600],
  ],
  'Europe/Busingen': [
    [3600, 'CET', 0],
    [7200, 'CEST', 354675600],
  ],
  'Europe/Chisinau': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 641944800],
    [7200, 'EET', 654652800],
  ],
  'Europe/Copenhagen': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323830800],
  ],
  'Europe/Dublin': [
    [3600, 'IST', 0],
    [0, 'GMT', 57722400],
  ],
  'Europe/Gibraltar': [
    [3600, 'CET', 0],
    [7200, 'CEST', 386125200],
  ],
  'Europe/Guernsey': [
    [3600, 'BST', 0],
    [0, 'GMT', 57722400],
  ],
  'Europe/Helsinki': [
    [7200, 'EET', 0],
    [10800, 'EEST', 354672000],
  ],
  'Europe/Isle_of_Man': [
    [3600, 'BST', 0],
    [0, 'GMT', 57722400],
  ],
  'Europe/Istanbul': [
    [7200, 'EET', 0],
    [10800, 'EEST', 107910000],
    [10800, '+03', 267915600],
    [10800, 'EEST', 482799600],
    [10800, '+03', 1473195600],
  ],
  'Europe/Jersey': [
    [3600, 'BST', 0],
    [0, 'GMT', 57722400],
  ],
  'Europe/Kaliningrad': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 606870000],
    [7200, 'EET', 622598400],
    [10800, '+03', 1301184000],
  ],
  'Europe/Kiev': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 646783200],
    [7200, 'EET', 686102400],
  ],
  'Europe/Kirov': [
    [14400, '+04', 0],
    [14400, 'MSD', 606866400],
    [10800, 'MSK', 622594800],
    [14400, '+04', 670374000],
    [14400, 'MSD', 701820000],
    [14400, 'MSK', 1301180400],
  ],
  'Europe/Kyiv': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 646783200],
    [7200, 'EET', 686102400],
  ],
  'Europe/Lisbon': [
    [3600, 'CET', 0],
    [0, 'WET', 212544000],
    [3600, 'WEST', 228268800],
    [3600, 'CET', 717555600],
    [7200, 'CEST', 733280400],
    [3600, 'WEST', 828234000],
  ],
  'Europe/Ljubljana': [
    [3600, 'CET', 0],
    [7200, 'CEST', 417574800],
  ],
  'Europe/London': [
    [3600, 'BST', 0],
    [0, 'GMT', 57722400],
  ],
  'Europe/Luxembourg': [
    [3600, 'CET', 0],
    [7200, 'CEST', 228877200],
  ],
  'Europe/Madrid': [
    [3600, 'CET', 0],
    [7200, 'CEST', 135122400],
  ],
  'Europe/Malta': [
    [3600, 'CET', 0],
    [7200, 'CEST', 12956400],
  ],
  'Europe/Mariehamn': [
    [7200, 'EET', 0],
    [10800, 'EEST', 354672000],
  ],
  'Europe/Minsk': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 670374000],
    [7200, 'EET', 686102400],
    [10800, '+03', 1301184000],
  ],
  'Europe/Monaco': [
    [3600, 'CET', 0],
    [7200, 'CEST', 196819200],
  ],
  'Europe/Moscow': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 670374000],
    [7200, 'EET', 686102400],
    [10800, 'MSK', 695779200],
    [14400, 'MSK', 1301180400],
  ],
  'Europe/Nicosia': [
    [7200, 'EET', 0],
    [10800, 'EEST', 166572000],
  ],
  'Europe/Oslo': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323830800],
  ],
  'Europe/Paris': [
    [3600, 'CET', 0],
    [7200, 'CEST', 196819200],
  ],
  'Europe/Podgorica': [
    [3600, 'CET', 0],
    [7200, 'CEST', 417574800],
  ],
  'Europe/Prague': [
    [3600, 'CET', 0],
    [7200, 'CEST', 291776400],
  ],
  'Europe/Riga': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 606870000],
    [7200, 'EET', 622598400],
  ],
  'Europe/Rome': [
    [3600, 'CET', 0],
    [7200, 'CEST', 12956400],
  ],
  'Europe/San_Marino': [
    [3600, 'CET', 0],
    [7200, 'CEST', 12956400],
  ],
  'Europe/Sarajevo': [
    [3600, 'CET', 0],
    [7200, 'CEST', 417574800],
  ],
  'Europe/Simferopol': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [7200, 'EET', 646786800],
    [10800, 'EEST', 701827200],
    [10800, 'MSK', 780447600],
    [10800, 'EEST', 859683600],
    [14400, 'MSK', 1396137600],
    [10800, 'MSK', 1414274400],
  ],
  'Europe/Skopje': [
    [3600, 'CET', 0],
    [7200, 'CEST', 417574800],
  ],
  'Europe/Sofia': [
    [7200, 'EET', 0],
    [10800, 'EEST', 291762000],
  ],
  'Europe/Stockholm': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323830800],
  ],
  'Europe/Tallinn': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 606870000],
    [7200, 'EET', 622598400],
  ],
  'Europe/Tirane': [
    [3600, 'CET', 0],
    [7200, 'CEST', 136854000],
  ],
  'Europe/Tiraspol': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 641944800],
    [7200, 'EET', 654652800],
  ],
  'Europe/Uzhgorod': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 646783200],
    [7200, 'EET', 686102400],
  ],
  'Europe/Vaduz': [
    [3600, 'CET', 0],
    [7200, 'CEST', 354675600],
  ],
  'Europe/Vatican': [
    [3600, 'CET', 0],
    [7200, 'CEST', 12956400],
  ],
  'Europe/Vienna': [
    [3600, 'CET', 0],
    [7200, 'CEST', 323823600],
  ],
  'Europe/Vilnius': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 606870000],
    [7200, 'EET', 622598400],
    [7200, 'CEST', 891133200],
    [3600, 'CET', 909277200],
    [7200, 'EET', 941331600],
  ],
  'Europe/Volgograd': [
    [14400, '+04', 0],
    [14400, 'MSD', 575416800],
    [10800, 'MSK', 591145200],
    [14400, '+04', 670374000],
    [14400, 'MSD', 701820000],
    [14400, 'MSK', 1301180400],
    [14400, '+04', 1540681200],
  ],
  'Europe/Warsaw': [
    [3600, 'CET', 0],
    [7200, 'CEST', 228873600],
  ],
  'Europe/Zagreb': [
    [3600, 'CET', 0],
    [7200, 'CEST', 417574800],
  ],
  'Europe/Zaporozhye': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 646783200],
    [7200, 'EET', 686102400],
  ],
  'Europe/Zurich': [
    [3600, 'CET', 0],
    [7200, 'CEST', 354675600],
  ],
  Factory: [[0, '-00', 0]],
  GB: [
    [3600, 'BST', 0],
    [0, 'GMT', 57722400],
  ],
  'GB-Eire': [
    [3600, 'BST', 0],
    [0, 'GMT', 57722400],
  ],
  GMT: [[0, 'GMT', 0]],
  'GMT+0': [[0, 'GMT', 0]],
  'GMT-0': [[0, 'GMT', 0]],
  GMT0: [[0, 'GMT', 0]],
  Greenwich: [[0, 'GMT', 0]],
  HST: [[-36000, 'HST', 0]],
  Hongkong: [
    [28800, 'HKT', 0],
    [32400, 'HKST', 9315000],
  ],
  Iceland: [[0, 'GMT', 0]],
  'Indian/Antananarivo': [[10800, 'EAT', 0]],
  'Indian/Comoro': [[10800, 'EAT', 0]],
  'Indian/Mayotte': [[10800, 'EAT', 0]],
  Israel: [
    [7200, 'IST', 0],
    [10800, 'IDT', 142380000],
  ],
  Jamaica: [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 126687600],
  ],
  Japan: [[32400, 'JST', 0]],
  Libya: [
    [7200, 'EET', 0],
    [3600, 'CET', 378684000],
    [7200, 'CEST', 386463600],
    [7200, 'EET', 641775600],
    [7200, 'CEST', 860108400],
    [7200, 'EET', 875916000],
    [7200, 'CEST', 1364515200],
    [7200, 'EET', 1382659200],
  ],
  MET: [
    [3600, 'CET', 0],
    [7200, 'CEST', 228877200],
  ],
  MST: [[-25200, 'MST', 0]],
  MST7MDT: [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
  ],
  'Mexico/BajaNorte': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
  ],
  'Mexico/BajaSur': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 828867600],
  ],
  'Mexico/General': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 828864000],
  ],
  NZ: [
    [43200, 'NZST', 0],
    [46800, 'NZDT', 152632800],
  ],
  Navajo: [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
  ],
  PRC: [
    [28800, 'CST', 0],
    [32400, 'CDT', 515527200],
  ],
  PST8PDT: [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
  ],
  'Pacific/Auckland': [
    [43200, 'NZST', 0],
    [46800, 'NZDT', 152632800],
  ],
  'Pacific/Guam': [
    [36000, 'GST', 0],
    [39600, 'GDT', 9907200],
    [36000, 'ChST', 977493600],
  ],
  'Pacific/Honolulu': [[-36000, 'HST', 0]],
  'Pacific/Johnston': [[-36000, 'HST', 0]],
  'Pacific/Midway': [[-39600, 'SST', 0]],
  'Pacific/Pago_Pago': [[-39600, 'SST', 0]],
  'Pacific/Saipan': [
    [36000, 'GST', 0],
    [39600, 'GDT', 9907200],
    [36000, 'ChST', 977493600],
  ],
  'Pacific/Samoa': [[-39600, 'SST', 0]],
  Poland: [
    [3600, 'CET', 0],
    [7200, 'CEST', 228873600],
  ],
  Portugal: [
    [3600, 'CET', 0],
    [0, 'WET', 212544000],
    [3600, 'WEST', 228268800],
    [3600, 'CET', 717555600],
    [7200, 'CEST', 733280400],
    [3600, 'WEST', 828234000],
  ],
  ROC: [
    [28800, 'CST', 0],
    [32400, 'CDT', 133977600],
  ],
  ROK: [
    [32400, 'KST', 0],
    [36000, 'KDT', 547578000],
  ],
  Turkey: [
    [7200, 'EET', 0],
    [10800, 'EEST', 107910000],
    [10800, '+03', 267915600],
    [10800, 'EEST', 482799600],
    [10800, '+03', 1473195600],
  ],
  UCT: [[0, 'UTC', 0]],
  'US/Alaska': [
    [-36000, 'AHST', 0],
    [-32400, 'AHDT', 9979200],
    [-32400, 'YST', 436359600],
    [-32400, 'AKST', 439030800],
    [-28800, 'AKDT', 452084400],
  ],
  'US/Aleutian': [
    [-39600, 'BST', 0],
    [-36000, 'BDT', 9982800],
    [-36000, 'AHST', 436363200],
    [-36000, 'HST', 439034400],
    [-32400, 'HDT', 452088000],
  ],
  'US/Arizona': [[-25200, 'MST', 0]],
  'US/Central': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
  ],
  'US/East-Indiana': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'US/Eastern': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 9961200],
  ],
  'US/Hawaii': [[-36000, 'HST', 0]],
  'US/Indiana-Starke': [
    [-21600, 'CST', 0],
    [-18000, 'CDT', 9964800],
    [-18000, 'EST', 688546800],
    [-18000, 'CDT', 1143961200],
  ],
  'US/Michigan': [
    [-18000, 'EST', 0],
    [-14400, 'EDT', 104914800],
  ],
  'US/Mountain': [
    [-25200, 'MST', 0],
    [-21600, 'MDT', 9968400],
  ],
  'US/Pacific': [
    [-28800, 'PST', 0],
    [-25200, 'PDT', 9972000],
  ],
  'US/Samoa': [[-39600, 'SST', 0]],
  UTC: [[0, 'UTC', 0]],
  Universal: [[0, 'UTC', 0]],
  'W-SU': [
    [10800, 'MSK', 0],
    [14400, 'MSD', 354920400],
    [10800, 'EEST', 670374000],
    [7200, 'EET', 686102400],
    [10800, 'MSK', 695779200],
    [14400, 'MSK', 1301180400],
  ],
  WET: [
    [3600, 'CET', 0],
    [0, 'WET', 212544000],
    [3600, 'WEST', 228268800],
    [3600, 'CET', 717555600],
    [7200, 'CEST', 733280400],
    [3600, 'WEST', 828234000],
  ],
  Zulu: [[0, 'UTC', 0]],
}
