GNU_LONG_OPTIONS: dict[str, tuple[tuple[str, ...], ...]] = {
    "base64": (
        ("--decode",),
        ("--ignore-garbage",),
        ("--wrap",),
        ("--help",),
        ("--version",),
    ),
    "basename": (
        ("--multiple",),
        ("--suffix",),
        ("--zero",),
        ("--help",),
        ("--version",),
    ),
    "cat": (
        ("--number-nonblank",),
        ("--number",),
        ("--squeeze-blank",),
        ("--show-nonprinting",),
        ("--show-ends",),
        ("--show-tabs",),
        ("--show-all",),
        ("--help",),
        ("--version",),
    ),
    "chmod": (
        ("--changes",),
        ("--dereference",),
        ("--recursive",),
        ("--no-dereference",),
        ("--no-preserve-root",),
        ("--preserve-root",),
        ("--quiet", "--silent"),
        ("--reference",),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "chgrp": (
        ("--recursive",),
        ("--changes",),
        ("--dereference",),
        ("--from",),
        ("--no-dereference",),
        ("--no-preserve-root",),
        ("--preserve-root",),
        ("--quiet", "--silent"),
        ("--reference",),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "chown": (
        ("--recursive",),
        ("--changes",),
        ("--dereference",),
        ("--from",),
        ("--no-dereference",),
        ("--no-preserve-root",),
        ("--preserve-root",),
        ("--quiet", "--silent"),
        ("--reference",),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "cmp": (
        ("--print-bytes",),
        ("--print-chars",),
        ("--ignore-initial",),
        ("--verbose",),
        ("--bytes",),
        ("--silent", "--quiet"),
        ("--version",),
        ("--help",),
    ),
    "comm": (
        ("--check-order",),
        ("--nocheck-order",),
        ("--output-delimiter",),
        ("--total",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "cp": (
        ("--archive",),
        ("--attributes-only",),
        ("--backup",),
        ("--copy-contents",),
        ("--debug",),
        ("--dereference",),
        ("--force",),
        ("--interactive",),
        ("--link",),
        ("--no-clobber",),
        ("--no-dereference",),
        ("--no-preserve",),
        ("--no-target-directory",),
        ("--one-file-system",),
        ("--parents", "--path"),
        ("--preserve",),
        ("--recursive",),
        ("--remove-destination",),
        ("--sparse",),
        ("--reflink",),
        ("--strip-trailing-slashes",),
        ("--suffix",),
        ("--symbolic-link",),
        ("--target-directory",),
        ("--update",),
        ("--verbose",),
        ("--keep-directory-symlink",),
        ("--help",),
        ("--version",),
    ),
    "csplit": (
        ("--digits",),
        ("--quiet",),
        ("--silent",),
        ("--keep-files",),
        ("--elide-empty-files",),
        ("--prefix",),
        ("--suffix-format",),
        ("--suppress-matched",),
        ("--help",),
        ("--version",),
    ),
    "cut": (
        ("--bytes",),
        ("--characters",),
        ("--fields",),
        ("--delimiter",),
        ("--only-delimited",),
        ("--output-delimiter",),
        ("--complement",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "date": (
        ("--date",),
        ("--debug",),
        ("--file",),
        ("--iso-8601",),
        ("--reference",),
        ("--resolution",),
        ("--rfc-email", "--rfc-822", "--rfc-2822"),
        ("--rfc-3339",),
        ("--set",),
        ("--uct", "--utc", "--universal"),
        ("--help",),
        ("--version",),
    ),
    "df": (
        ("--all",),
        ("--block-size",),
        ("--inodes",),
        ("--human-readable",),
        ("--si",),
        ("--local",),
        ("--output",),
        ("--portability",),
        ("--print-type",),
        ("--sync",),
        ("--no-sync",),
        ("--total",),
        ("--type",),
        ("--exclude-type",),
        ("--help",),
        ("--version",),
    ),
    "diff": (
        ("--binary",),
        ("--brief",),
        ("--changed-group-format",),
        ("--color",),
        ("--context",),
        ("--ed",),
        ("--exclude",),
        ("--exclude-from",),
        ("--expand-tabs",),
        ("--forward-ed",),
        ("--from-file",),
        ("--help",),
        ("--horizon-lines",),
        ("--ifdef",),
        ("--ignore-all-space",),
        ("--ignore-blank-lines",),
        ("--ignore-case",),
        ("--ignore-file-name-case",),
        ("--ignore-matching-lines",),
        ("--ignore-space-change",),
        ("--ignore-tab-expansion",),
        ("--ignore-trailing-space",),
        ("--inhibit-hunk-merge",),
        ("--initial-tab",),
        ("--label",),
        ("--left-column",),
        ("--line-format",),
        ("--minimal",),
        ("--new-file",),
        ("--new-group-format",),
        ("--new-line-format",),
        ("--no-dereference",),
        ("--no-ignore-file-name-case",),
        ("--normal",),
        ("--old-group-format",),
        ("--old-line-format",),
        ("--paginate",),
        ("--palette",),
        ("--rcs",),
        ("--recursive",),
        ("--report-identical-files",),
        ("--sdiff-merge-assist",),
        ("--show-c-function",),
        ("--show-function-line",),
        ("--side-by-side",),
        ("--speed-large-files",),
        ("--starting-file",),
        ("--strip-trailing-cr",),
        ("--suppress-blank-empty",),
        ("--suppress-common-lines",),
        ("--tabsize",),
        ("--text",),
        ("--to-file",),
        ("--unchanged-group-format",),
        ("--unchanged-line-format",),
        ("--unidirectional-new-file",),
        ("--unified",),
        ("--version",),
        ("--width",),
        ("---no-directory",),
        ("---presume-output-tty",),
    ),
    "dirname": (("--zero",), ("--help",), ("--version",)),
    "du": (
        ("--all",),
        ("--apparent-size",),
        ("--block-size",),
        ("--bytes",),
        ("--count-links",),
        ("---debug",),
        ("--dereference",),
        ("--dereference-args",),
        ("--exclude",),
        ("--exclude-from",),
        ("--files0-from",),
        ("--human-readable",),
        ("--inodes",),
        ("--si",),
        ("--max-depth",),
        ("--null",),
        ("--no-dereference",),
        ("--one-file-system",),
        ("--separate-dirs",),
        ("--summarize",),
        ("--total",),
        ("--threshold",),
        ("--time",),
        ("--time-style",),
        ("--help",),
        ("--version",),
    ),
    "expand": (("--tabs",), ("--initial",), ("--help",), ("--version",)),
    "fmt": (
        ("--crown-margin",),
        ("--prefix",),
        ("--split-only",),
        ("--tagged-paragraph",),
        ("--uniform-spacing",),
        ("--width",),
        ("--goal",),
        ("--help",),
        ("--version",),
    ),
    "fold": (
        ("--bytes",),
        ("--spaces",),
        ("--width",),
        ("--help",),
        ("--version",),
    ),
    "grep": (
        ("--basic-regexp",),
        ("--extended-regexp",),
        ("--fixed-regexp", "--fixed-strings"),
        ("--perl-regexp",),
        ("--after-context",),
        ("--before-context",),
        ("--binary-files",),
        ("--byte-offset",),
        ("--context",),
        ("--color", "--colour"),
        ("--count",),
        ("--devices",),
        ("--directories",),
        ("--exclude",),
        ("--exclude-from",),
        ("--exclude-dir",),
        ("--file",),
        ("--files-with-matches",),
        ("--files-without-match",),
        ("--group-separator",),
        ("--help",),
        ("--include",),
        ("--ignore-case",),
        ("--no-ignore-case",),
        ("--initial-tab",),
        ("--label",),
        ("--line-buffered",),
        ("--line-number",),
        ("--line-regexp",),
        ("--max-count",),
        ("--no-filename",),
        ("--no-group-separator",),
        ("--no-messages",),
        ("--null",),
        ("--null-data",),
        ("--only-matching",),
        ("--quiet", "--silent"),
        ("--recursive",),
        ("--dereference-recursive",),
        ("--regexp",),
        ("--invert-match",),
        ("--text",),
        ("--binary",),
        ("--unix-byte-offsets",),
        ("--version",),
        ("--with-filename",),
        ("--word-regexp",),
    ),
    "gunzip": (
        ("--ascii",),
        ("--to-stdout", "--stdout"),
        ("--decompress", "--uncompress"),
        ("--force",),
        ("--help",),
        ("--keep",),
        ("--list",),
        ("--license",),
        ("--no-name",),
        ("--name",),
        ("---presume-input-tty",),
        ("--quiet", "--silent"),
        ("--synchronous",),
        ("--recursive",),
        ("--suffix",),
        ("--test",),
        ("--verbose",),
        ("--version",),
        ("--fast",),
        ("--best",),
        ("--lzw",),
        ("--bits",),
        ("--rsyncable",),
    ),
    "gzip": (
        ("--ascii",),
        ("--to-stdout", "--stdout"),
        ("--decompress", "--uncompress"),
        ("--force",),
        ("--help",),
        ("--keep",),
        ("--list",),
        ("--license",),
        ("--no-name",),
        ("--name",),
        ("---presume-input-tty",),
        ("--quiet", "--silent"),
        ("--synchronous",),
        ("--recursive",),
        ("--suffix",),
        ("--test",),
        ("--verbose",),
        ("--version",),
        ("--fast",),
        ("--best",),
        ("--lzw",),
        ("--bits",),
        ("--rsyncable",),
    ),
    "head": (
        ("--bytes",),
        ("--lines",),
        ("---presume-input-pipe",),
        ("--quiet", "--silent"),
        ("--verbose",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "join": (
        ("--ignore-case",),
        ("--check-order",),
        ("--nocheck-order",),
        ("--zero-terminated",),
        ("--header",),
        ("--help",),
        ("--version",),
    ),
    "ln": (
        ("--backup",),
        ("--directory",),
        ("--no-dereference",),
        ("--no-target-directory",),
        ("--force",),
        ("--interactive",),
        ("--suffix",),
        ("--target-directory",),
        ("--logical",),
        ("--physical",),
        ("--relative",),
        ("--symbolic",),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "ls": (
        ("--all",),
        ("--escape",),
        ("--directory",),
        ("--dired",),
        ("--full-time",),
        ("--group-directories-first",),
        ("--human-readable",),
        ("--inode",),
        ("--kibibytes",),
        ("--numeric-uid-gid",),
        ("--no-group",),
        ("--hide-control-chars",),
        ("--reverse",),
        ("--size",),
        ("--width",),
        ("--almost-all",),
        ("--ignore-backups",),
        ("--classify",),
        ("--file-type",),
        ("--si",),
        ("--dereference-command-line",),
        ("--dereference-command-line-symlink-to-dir",),
        ("--hide",),
        ("--ignore",),
        ("--indicator-style",),
        ("--dereference",),
        ("--literal",),
        ("--quote-name",),
        ("--quoting-style",),
        ("--recursive",),
        ("--format",),
        ("--show-control-chars",),
        ("--sort",),
        ("--tabsize",),
        ("--time",),
        ("--time-style",),
        ("--zero",),
        ("--color",),
        ("--hyperlink",),
        ("--block-size",),
        ("--context",),
        ("--author",),
        ("--help",),
        ("--version",),
    ),
    "md5sum": (
        ("--check",),
        ("--ignore-missing",),
        ("--quiet",),
        ("--status",),
        ("--warn",),
        ("--strict",),
        ("--tag",),
        ("--zero",),
        ("--binary",),
        ("--text",),
        ("--help",),
        ("--version",),
    ),
    "mkdir": (
        ("--mode",),
        ("--parents",),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "mktemp": (
        ("--directory",),
        ("--quiet",),
        ("--dry-run",),
        ("--suffix",),
        ("--tmpdir",),
        ("--help",),
        ("--version",),
    ),
    "mv": (
        ("--backup",),
        ("--context",),
        ("--debug",),
        ("--exchange",),
        ("--force",),
        ("--interactive",),
        ("--no-clobber",),
        ("--no-copy",),
        ("--no-target-directory",),
        ("--strip-trailing-slashes",),
        ("--suffix",),
        ("--target-directory",),
        ("--update",),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "nl": (
        ("--header-numbering",),
        ("--body-numbering",),
        ("--footer-numbering",),
        ("--starting-line-number",),
        ("--line-increment",),
        ("--no-renumber",),
        ("--join-blank-lines",),
        ("--number-separator",),
        ("--number-width",),
        ("--number-format",),
        ("--section-delimiter",),
        ("--help",),
        ("--version",),
    ),
    "numfmt": (
        ("--from",),
        ("--from-unit",),
        ("--to",),
        ("--to-unit",),
        ("--round",),
        ("--padding",),
        ("--suffix",),
        ("--grouping",),
        ("--delimiter",),
        ("--field",),
        ("--debug",),
        ("---debug",),
        ("--header",),
        ("--format",),
        ("--invalid",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "od": (
        ("--skip-bytes",),
        ("--address-radix",),
        ("--read-bytes",),
        ("--format",),
        ("--output-duplicates",),
        ("--strings",),
        ("--traditional",),
        ("--width",),
        ("--endian",),
        ("--help",),
        ("--version",),
    ),
    "paste": (
        ("--serial",),
        ("--delimiters",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "pwd": (("--logical",), ("--physical",), ("--help",), ("--version",)),
    "readlink": (
        ("--canonicalize",),
        ("--canonicalize-existing",),
        ("--canonicalize-missing",),
        ("--no-newline",),
        ("--quiet",),
        ("--silent",),
        ("--verbose",),
        ("--zero",),
        ("--help",),
        ("--version",),
    ),
    "realpath": (
        ("--canonicalize-existing",),
        ("--canonicalize-missing",),
        ("--relative-to",),
        ("--relative-base",),
        ("--quiet",),
        ("--strip", "--no-symlinks"),
        ("--zero",),
        ("--logical",),
        ("--physical",),
        ("--help",),
        ("--version",),
    ),
    "rm": (
        ("--force",),
        ("--interactive",),
        ("--one-file-system",),
        ("--no-preserve-root",),
        ("--preserve-root",),
        ("---presume-input-tty",),
        ("--recursive",),
        ("--dir",),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "rmdir": (
        ("--ignore-fail-on-non-empty",),
        ("--path", "--parents"),
        ("--verbose",),
        ("--help",),
        ("--version",),
    ),
    "seq": (
        ("--equal-width",),
        ("--format",),
        ("--separator",),
        ("--help",),
        ("--version",),
    ),
    "sha1sum": (
        ("--check",),
        ("--ignore-missing",),
        ("--quiet",),
        ("--status",),
        ("--warn",),
        ("--strict",),
        ("--tag",),
        ("--zero",),
        ("--binary",),
        ("--text",),
        ("--help",),
        ("--version",),
    ),
    "sha256sum": (
        ("--check",),
        ("--ignore-missing",),
        ("--quiet",),
        ("--status",),
        ("--warn",),
        ("--strict",),
        ("--tag",),
        ("--zero",),
        ("--binary",),
        ("--text",),
        ("--help",),
        ("--version",),
    ),
    "sha384sum": (
        ("--check",),
        ("--ignore-missing",),
        ("--quiet",),
        ("--status",),
        ("--warn",),
        ("--strict",),
        ("--tag",),
        ("--zero",),
        ("--binary",),
        ("--text",),
        ("--help",),
        ("--version",),
    ),
    "sha512sum": (
        ("--check",),
        ("--ignore-missing",),
        ("--quiet",),
        ("--status",),
        ("--warn",),
        ("--strict",),
        ("--tag",),
        ("--zero",),
        ("--binary",),
        ("--text",),
        ("--help",),
        ("--version",),
    ),
    "shuf": (
        ("--echo",),
        ("--input-range",),
        ("--head-count",),
        ("--output",),
        ("--random-source",),
        ("--repeat",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "sort": (
        ("--ignore-leading-blanks",),
        ("--check",),
        ("--compress-program",),
        ("--debug",),
        ("--dictionary-order",),
        ("--ignore-case",),
        ("--files0-from",),
        ("--general-numeric-sort",),
        ("--ignore-nonprinting",),
        ("--key",),
        ("--merge",),
        ("--month-sort",),
        ("--numeric-sort",),
        ("--human-numeric-sort",),
        ("--version-sort",),
        ("--random-sort",),
        ("--random-source",),
        ("--sort",),
        ("--output",),
        ("--reverse",),
        ("--stable",),
        ("--batch-size",),
        ("--buffer-size",),
        ("--field-separator",),
        ("--temporary-directory",),
        ("--unique",),
        ("--zero-terminated",),
        ("--parallel",),
        ("--help",),
        ("--version",),
    ),
    "split": (
        ("--bytes",),
        ("--lines",),
        ("--line-bytes",),
        ("--number",),
        ("--elide-empty-files",),
        ("--unbuffered",),
        ("--suffix-length",),
        ("--additional-suffix",),
        ("--numeric-suffixes",),
        ("--hex-suffixes",),
        ("--filter",),
        ("--verbose",),
        ("--separator",),
        ("---io-blksize",),
        ("--help",),
        ("--version",),
    ),
    "stat": (
        ("--dereference",),
        ("--file-system",),
        ("--format",),
        ("--printf",),
        ("--terse",),
        ("--cached",),
        ("--help",),
        ("--version",),
    ),
    "tac": (
        ("--before",),
        ("--regex",),
        ("--separator",),
        ("--help",),
        ("--version",),
    ),
    "tail": (
        ("--bytes",),
        ("--follow",),
        ("--lines",),
        ("--max-unchanged-stats",),
        ("---disable-inotify",),
        ("--pid",),
        ("---presume-input-pipe",),
        ("--quiet", "--silent"),
        ("--retry",),
        ("--sleep-interval",),
        ("--verbose",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "tee": (
        ("--append",),
        ("--ignore-interrupts",),
        ("--output-error",),
        ("--help",),
        ("--version",),
    ),
    "touch": (
        ("--time",),
        ("--no-create",),
        ("--date",),
        ("--reference",),
        ("--no-dereference",),
        ("--help",),
        ("--version",),
    ),
    "tr": (
        ("--complement",),
        ("--delete",),
        ("--squeeze-repeats",),
        ("--truncate-set1",),
        ("--help",),
        ("--version",),
    ),
    "truncate": (
        ("--no-create",),
        ("--io-blocks",),
        ("--reference",),
        ("--size",),
        ("--help",),
        ("--version",),
    ),
    "unexpand": (
        ("--tabs",),
        ("--all",),
        ("--first-only",),
        ("--help",),
        ("--version",),
    ),
    "uniq": (
        ("--count",),
        ("--repeated",),
        ("--all-repeated",),
        ("--group",),
        ("--ignore-case",),
        ("--unique",),
        ("--skip-fields",),
        ("--skip-chars",),
        ("--check-chars",),
        ("--zero-terminated",),
        ("--help",),
        ("--version",),
    ),
    "wc": (
        ("--bytes",),
        ("--chars",),
        ("--lines",),
        ("--words",),
        ("--debug",),
        ("--files0-from",),
        ("--max-line-length",),
        ("--total",),
        ("--help",),
        ("--version",),
    ),
    "zcat": (
        ("--ascii",),
        ("--to-stdout", "--stdout"),
        ("--decompress", "--uncompress"),
        ("--force",),
        ("--help",),
        ("--keep",),
        ("--list",),
        ("--license",),
        ("--no-name",),
        ("--name",),
        ("---presume-input-tty",),
        ("--quiet", "--silent"),
        ("--synchronous",),
        ("--recursive",),
        ("--suffix",),
        ("--test",),
        ("--verbose",),
        ("--version",),
        ("--fast",),
        ("--best",),
        ("--lzw",),
        ("--bits",),
        ("--rsyncable",),
    ),
}

# GNU coreutils 9.7, grep 3.11, diffutils 3.10 and gzip 1.13 getopt tables.
# Only names, argument arity and option identity are taken from the pinned
# upstream tables. Unsupported options participate in ambiguity without
# becoming supported commands. The declarations remain the capability gate.
