# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========

from mirage.commands.cli.builtin.gh import actions as action_commands
from mirage.commands.cli.builtin.gh import issue as issue_commands
from mirage.commands.cli.builtin.gh import pull as pull_commands
from mirage.commands.cli.builtin.gh import release as release_commands
from mirage.commands.cli.builtin.gh import repo as repo_commands
from mirage.commands.cli.builtin.gh.api import api
from mirage.commands.cli.types import CLISpec
from mirage.commands.spec.types import Operand, Option
from mirage.core.github.config import GhConfig

REPO = Option(short="-R",
              long="--repo",
              type="str",
              description="Select another repository, as [HOST/]OWNER/REPO")
JSON = Option(long="--json",
              type="str",
              description="Output selected JSON fields")
JQ = Option(short="-q",
            long="--jq",
            type="str",
            description="Filter JSON output")
LIMIT_30 = Option(short="-L", long="--limit", type="int", default="30")
BODY = Option(short="-b", long="--body", type="str")
BODY_FILE = Option(short="-F", long="--body-file", type="path")
TITLE = Option(short="-t", long="--title", type="str")
NUMBER = Operand(type="str", name="NUMBER", required=True)


def _issue() -> CLISpec:
    return CLISpec(name="issue",
                   description="Manage issues",
                   subcommands=(
                       CLISpec(name="list",
                               aliases=("ls", ),
                               description="List issues",
                               fn=issue_commands.list_cmd,
                               options=(REPO, JSON, JQ, LIMIT_30,
                                        Option(short="-s",
                                               long="--state",
                                               type="str",
                                               choices=("open", "closed",
                                                        "all"),
                                               default="open"),
                                        Option(short="-a",
                                               long="--assignee",
                                               type="str"),
                                        Option(short="-A",
                                               long="--author",
                                               type="str"),
                                        Option(short="-l",
                                               long="--label",
                                               type="str",
                                               multiple=True))),
                       CLISpec(name="view",
                               description="View an issue",
                               fn=issue_commands.view_cmd,
                               positional=(NUMBER, ),
                               options=(REPO, JSON, JQ)),
                       CLISpec(name="create",
                               aliases=("new", ),
                               description="Create an issue",
                               fn=issue_commands.create_cmd,
                               write=True,
                               options=(REPO, TITLE, BODY, BODY_FILE,
                                        Option(short="-a",
                                               long="--assignee",
                                               type="str",
                                               multiple=True),
                                        Option(short="-l",
                                               long="--label",
                                               type="str",
                                               multiple=True))),
                       CLISpec(name="edit",
                               description="Edit an issue",
                               fn=issue_commands.edit_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, TITLE, BODY, BODY_FILE,
                                        Option(long="--add-assignee",
                                               type="str",
                                               multiple=True),
                                        Option(long="--remove-assignee",
                                               type="str",
                                               multiple=True),
                                        Option(long="--add-label",
                                               type="str",
                                               multiple=True),
                                        Option(long="--remove-label",
                                               type="str",
                                               multiple=True))),
                       CLISpec(name="close",
                               description="Close an issue",
                               fn=issue_commands.close_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, )),
                       CLISpec(name="reopen",
                               description="Reopen an issue",
                               fn=issue_commands.reopen_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, )),
                       CLISpec(name="comment",
                               description="Add a comment to an issue",
                               fn=issue_commands.comment_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, BODY, BODY_FILE)),
                   ))


def _pr() -> CLISpec:
    return CLISpec(name="pr",
                   description="Manage pull requests",
                   subcommands=(
                       CLISpec(name="list",
                               aliases=("ls", ),
                               description="List pull requests",
                               fn=pull_commands.list_cmd,
                               options=(REPO, JSON, JQ, LIMIT_30,
                                        Option(short="-s",
                                               long="--state",
                                               type="str",
                                               choices=("open", "closed",
                                                        "merged", "all"),
                                               default="open"),
                                        Option(short="-B",
                                               long="--base",
                                               type="str"),
                                        Option(short="-H",
                                               long="--head",
                                               type="str"))),
                       CLISpec(name="view",
                               description="View a pull request",
                               fn=pull_commands.view_cmd,
                               positional=(NUMBER, ),
                               options=(REPO, JSON, JQ)),
                       CLISpec(name="create",
                               aliases=("new", ),
                               description="Create a pull request",
                               fn=pull_commands.create_cmd,
                               write=True,
                               options=(REPO, TITLE, BODY, BODY_FILE,
                                        Option(short="-H",
                                               long="--head",
                                               type="str"),
                                        Option(short="-B",
                                               long="--base",
                                               type="str"),
                                        Option(short="-d", long="--draft"),
                                        Option(long="--no-maintainer-edit"))),
                       CLISpec(name="edit",
                               description="Edit a pull request",
                               fn=pull_commands.edit_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, TITLE, BODY, BODY_FILE,
                                        Option(short="-B",
                                               long="--base",
                                               type="str"))),
                       CLISpec(name="merge",
                               description="Merge a pull request",
                               fn=pull_commands.merge_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, BODY, BODY_FILE,
                                        Option(short="-m", long="--merge"),
                                        Option(short="-r", long="--rebase"),
                                        Option(short="-s", long="--squash"),
                                        Option(short="-t",
                                               long="--subject",
                                               type="str"),
                                        Option(long="--match-head-commit",
                                               type="str"))),
                       CLISpec(name="close",
                               description="Close a pull request",
                               fn=pull_commands.close_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, )),
                       CLISpec(name="comment",
                               description="Add a comment to a pull request",
                               fn=pull_commands.comment_cmd,
                               write=True,
                               positional=(NUMBER, ),
                               options=(REPO, BODY, BODY_FILE)),
                       CLISpec(name="diff",
                               description="View changes in a pull request",
                               fn=pull_commands.diff_cmd,
                               positional=(NUMBER, ),
                               options=(REPO, )),
                       CLISpec(name="checks",
                               description="Show CI checks for a pull request",
                               fn=pull_commands.checks_cmd,
                               positional=(NUMBER, ),
                               options=(REPO, JSON, JQ)),
                   ))


def _repo() -> CLISpec:
    return CLISpec(name="repo",
                   description="Manage repositories",
                   subcommands=(
                       CLISpec(name="list",
                               aliases=("ls", ),
                               description="List repositories",
                               fn=repo_commands.list_cmd,
                               positional=(Operand(type="str",
                                                   name="OWNER"), ),
                               options=(JSON, JQ, LIMIT_30)),
                       CLISpec(name="view",
                               description="View a repository",
                               fn=repo_commands.view,
                               positional=(Operand(type="str",
                                                   name="REPOSITORY"), ),
                               options=(REPO, JSON, JQ)),
                       CLISpec(name="create",
                               description="Create a repository",
                               fn=repo_commands.create_cmd,
                               write=True,
                               positional=(Operand(type="str", name="NAME"), ),
                               options=(Option(long="--public"),
                                        Option(long="--private"),
                                        Option(short="-d",
                                               long="--description",
                                               type="str"),
                                        Option(short="-h",
                                               long="--homepage",
                                               type="str"),
                                        Option(long="--add-readme"))),
                       CLISpec(name="fork",
                               description="Create a fork of a repository",
                               fn=repo_commands.fork,
                               write=True,
                               positional=(Operand(type="str",
                                                   name="REPOSITORY"), ),
                               options=(Option(long="--fork-name",
                                               type="str"), )),
                       CLISpec(name="rename",
                               description="Rename a repository",
                               fn=repo_commands.rename,
                               write=True,
                               positional=(Operand(type="str",
                                                   name="NEW-NAME",
                                                   required=True), ),
                               options=(REPO, )),
                   ))


def _release() -> CLISpec:
    return CLISpec(name="release",
                   description="Manage releases",
                   subcommands=(
                       CLISpec(name="list",
                               aliases=("ls", ),
                               description="List releases",
                               fn=release_commands.list_cmd,
                               options=(REPO, JSON, JQ, LIMIT_30)),
                       CLISpec(name="view",
                               description="View a release",
                               fn=release_commands.view_cmd,
                               positional=(Operand(type="str",
                                                   name="TAG",
                                                   required=True), ),
                               options=(REPO, JSON, JQ)),
                       CLISpec(name="create",
                               description="Create a release",
                               fn=release_commands.create_cmd,
                               write=True,
                               positional=(Operand(type="str",
                                                   name="TAG",
                                                   required=True), ),
                               options=(REPO,
                                        Option(short="-n",
                                               long="--notes",
                                               type="str"),
                                        Option(short="-F",
                                               long="--notes-file",
                                               type="path"), TITLE,
                                        Option(short="-d", long="--draft"),
                                        Option(short="-p",
                                               long="--prerelease"),
                                        Option(long="--generate-notes"),
                                        Option(long="--target", type="str"))),
                   ))


def _run() -> CLISpec:
    return CLISpec(name="run",
                   description="View workflow runs",
                   subcommands=(
                       CLISpec(name="list",
                               aliases=("ls", ),
                               description="List workflow runs",
                               fn=action_commands.run_list_cmd,
                               options=(REPO, JSON, JQ,
                                        Option(short="-L",
                                               long="--limit",
                                               type="int",
                                               default="20"),
                                        Option(short="-b",
                                               long="--branch",
                                               type="str"),
                                        Option(short="-c",
                                               long="--commit",
                                               type="str"),
                                        Option(long="--created", type="str"),
                                        Option(short="-e",
                                               long="--event",
                                               type="str"),
                                        Option(short="-s",
                                               long="--status",
                                               type="str"),
                                        Option(short="-u",
                                               long="--user",
                                               type="str"),
                                        Option(short="-w",
                                               long="--workflow",
                                               type="str"))),
                       CLISpec(name="view",
                               description="View a workflow run",
                               fn=action_commands.run_view_cmd,
                               positional=(Operand(type="str",
                                                   name="RUN-ID",
                                                   required=True), ),
                               options=(REPO, JSON, JQ,
                                        Option(long="--exit-status"))),
                       CLISpec(name="rerun",
                               description="Rerun a workflow run",
                               fn=action_commands.run_rerun_cmd,
                               write=True,
                               positional=(Operand(type="str",
                                                   name="RUN-ID",
                                                   required=True), ),
                               options=(REPO, Option(short="-d",
                                                     long="--debug"),
                                        Option(long="--failed"),
                                        Option(short="-j",
                                               long="--job",
                                               type="str"))),
                   ))


def _workflow() -> CLISpec:
    return CLISpec(name="workflow",
                   description="Manage workflows",
                   subcommands=(
                       CLISpec(name="list",
                               aliases=("ls", ),
                               description="List workflows",
                               fn=action_commands.workflow_list_cmd,
                               options=(REPO, JSON, JQ,
                                        Option(short="-L",
                                               long="--limit",
                                               type="int",
                                               default="50"),
                                        Option(short="-a", long="--all"))),
                       CLISpec(name="view",
                               description="View a workflow",
                               fn=action_commands.workflow_view_cmd,
                               positional=(Operand(type="str",
                                                   name="WORKFLOW",
                                                   required=True), ),
                               options=(REPO, )),
                       CLISpec(name="run",
                               description="Run a workflow",
                               fn=action_commands.workflow_run_cmd,
                               write=True,
                               positional=(Operand(type="str",
                                                   name="WORKFLOW",
                                                   required=True), ),
                               options=(REPO,
                                        Option(short="-r",
                                               long="--ref",
                                               type="str"),
                                        Option(short="-f",
                                               long="--raw-field",
                                               type="str",
                                               multiple=True),
                                        Option(short="-F",
                                               long="--field",
                                               type="str",
                                               multiple=True),
                                        Option(long="--json"))),
                   ))


GH = CLISpec(
    name="gh",
    description="GitHub CLI",
    config_model=GhConfig,
    subcommands=(
        CLISpec(name="api",
                description="Make an authenticated GitHub API request",
                fn=api,
                write=True,
                positional=(Operand(type="str", name="ENDPOINT",
                                    required=True), ),
                options=(
                    Option(short="-X", long="--method", type="str"),
                    Option(short="-f",
                           long="--raw-field",
                           type="str",
                           multiple=True),
                    Option(short="-F",
                           long="--field",
                           type="str",
                           multiple=True),
                    Option(short="-H",
                           long="--header",
                           type="str",
                           multiple=True),
                    Option(long="--input", type="path"),
                    JQ,
                    Option(long="--paginate"),
                    Option(long="--slurp"),
                    Option(long="--silent"),
                )),
        _issue(),
        _pr(),
        _repo(),
        _release(),
        _run(),
        _workflow(),
    ),
)
