# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========

from mirage.context.session_context import (
    DEFAULT_UMASK,
    RedirectOpener,
    RefusalSink,
    clear_program_invocation,
    dotglob_active,
    effective_mount_mode,
    effective_path_mode,
    explaining,
    get_admission,
    get_current_evaluation,
    get_current_session,
    get_current_session_for,
    get_current_session_unless_foreign,
    get_mount_gate,
    get_walk_probe,
    hidden_refusal,
    line_running,
    note_refusal,
    program_invocation,
    readonly_below,
    redirect_opener_for,
    redirect_paths_for,
    redirect_target_judged,
    require_mount_writable,
    require_paths_writable,
    reset_admission,
    reset_current_session,
    reset_explaining,
    reset_mount_gate,
    reset_program_invocation,
    reset_redirect_paths,
    reset_refusal_sink,
    reset_walk_probe,
    session_umask,
    session_visibility,
    set_admission,
    set_current_evaluation,
    set_current_session,
    set_explaining,
    set_mount_gate,
    set_program_invocation,
    set_redirect_paths,
    set_refusal_sink,
    set_walk_probe,
    strongest_mode_under,
    strongest_under_session,
)

__all__ = [
    "DEFAULT_UMASK",
    "dotglob_active",
    "effective_mount_mode",
    "effective_path_mode",
    "get_admission",
    "clear_program_invocation",
    "get_current_evaluation",
    "get_current_session",
    "program_invocation",
    "reset_program_invocation",
    "set_program_invocation",
    "get_current_session_for",
    "get_current_session_unless_foreign",
    "get_mount_gate",
    "get_walk_probe",
    "explaining",
    "line_running",
    "note_refusal",
    "reset_explaining",
    "set_explaining",
    "hidden_refusal",
    "readonly_below",
    "require_paths_writable",
    "RedirectOpener",
    "RefusalSink",
    "redirect_opener_for",
    "redirect_paths_for",
    "redirect_target_judged",
    "require_mount_writable",
    "reset_admission",
    "reset_mount_gate",
    "reset_redirect_paths",
    "reset_refusal_sink",
    "reset_walk_probe",
    "session_umask",
    "session_visibility",
    "reset_current_session",
    "set_admission",
    "set_current_evaluation",
    "set_current_session",
    "set_mount_gate",
    "set_redirect_paths",
    "set_refusal_sink",
    "set_walk_probe",
    "strongest_mode_under",
    "strongest_under_session",
]
