# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

SKILLS_DIR = ROOT / "plugins/mirage/skills"
PY_OUT = ROOT / "python/mirage/commands/cli/generated/skills_data.py"
TS_OUT = (ROOT / "typescript/packages/core/src/commands/cli/generated" /
          "skills_data.ts")

LICENSE_PY = (ROOT / "scripts/gen_specs.py").read_text().split("\n")[:13]

NOTE = ("GENERATED by scripts/gen_skills.py from plugins/mirage/skills/*/"
        "SKILL.md.\nDo not edit by hand; edit the skill, rerun the script "
        "and commit both trees' output together.")


def load_skills() -> dict[str, str]:
    """Every skill directory's SKILL.md text, keyed by directory name."""
    skills: dict[str, str] = {}
    for path in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        skills[path.parent.name] = path.read_text(encoding="utf-8")
    return skills


def render_py(skills: dict[str, str]) -> str:
    head = "\n".join(LICENSE_PY)
    note = "\n".join("# " + line for line in NOTE.split("\n"))
    rows = "".join(
        f"    {json.dumps(name)}: {json.dumps(text, ensure_ascii=False)},\n"
        for name, text in skills.items())
    return f"{head}\n\n{note}\n\nSKILLS: dict[str, str] = {{\n{rows}}}\n"


def render_ts(skills: dict[str, str]) -> str:
    head = "\n".join("//" + line[1:] for line in LICENSE_PY)
    note = "\n".join("// " + line for line in NOTE.split("\n"))
    rows = "".join(f"  {json.dumps(name)}: {json.dumps(text)},\n"
                   for name, text in skills.items())
    return (f"{head}\n\n{note}\n\n"
            f"export const SKILLS: Readonly<Record<string, string>> = {{\n"
            f"{rows}}}\n")


def main(argv: list[str]) -> int:
    skills = load_skills()
    py = render_py(skills)
    ts = render_ts(skills)
    if "--check" in argv:
        stale = [
            str(p.relative_to(ROOT))
            for p, want in ((PY_OUT, py), (TS_OUT, ts))
            if not p.exists() or p.read_text(encoding="utf-8") != want
        ]
        for p in stale:
            print(f"stale: {p} (run scripts/gen_skills.py)")
        return 1 if stale else 0
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    (PY_OUT.parent / "__init__.py").write_text("\n".join(LICENSE_PY) + "\n")
    PY_OUT.write_text(py, encoding="utf-8")
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(ts, encoding="utf-8")
    print(f"wrote {len(skills)} skills: {', '.join(skills)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
