# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
"""Regenerate the tzdata abbreviation table TypeScript's ``date`` reads.

Usage, from the repo root::

    ./python/.venv/bin/python scripts/gen_tz_abbrevs.py

Python renders ``%Z`` straight from tzdata through ``zoneinfo``; Intl
offers no tzdata names (``GMT+8`` where tzdata says ``HKT``), so the
TypeScript twin ships this table instead, sampled from the same
``zoneinfo`` by ``mirage.utils.timezone.zone_abbreviations``. Rerun it
when tzdata renames a zone's abbreviation; ``tests/utils/test_timezone.py``
pins a set of well-known zones against the committed file.
"""

import re
import sys
import zoneinfo
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "python"))

from mirage.utils.timezone import zone_abbreviations  # noqa: E402

OUT = (ROOT / "typescript" / "packages" / "core" / "src" / "utils" /
       "tz_abbrevs.ts")
LICENSE = """\
// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
"""
PREAMBLE = """// Generated by scripts/gen_tz_abbrevs.py; do not edit by hand.
//
// The abbreviations every tzdata zone has carried since 1970: one row per
// name an offset has shown, `[offset in seconds east, name, the epoch
// second it took effect]`, in the order the names took effect, with 0 for
// the rows in effect at 1970. This is what GNU date prints for `%Z` and
// what Python's zoneinfo renders; Intl only offers `GMT+8`, so the
// TypeScript `date` looks the name up here by the offset Intl does report
// and the instant rendered (tzAbbreviation). An offset tzdata only ever
// spelled out (`+08`, `-03`) has no row and renders that way; one that
// carried letters at some time keeps every name it carried, so Moscow's
// +04 reads MSD before 2011 and MSK after, and Istanbul's +03 reads EEST
// in the summers before 2016 and +03 since.
"""
# Not zones: `posixrules` is glibc's default-rule file and `localtime` the
# host's own link.
SKIPPED = frozenset({"posixrules", "localtime"})
# A key prettier leaves unquoted (`quoteProps: as-needed`): `CET`, `Cuba`.
BARE_KEY = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def render(rows: list[tuple[str, list[tuple[int, str, int]]]]) -> str:
    """The TypeScript module for ``rows``, in the shape prettier keeps.

    Args:
        rows (list[tuple[str, list[tuple[int, str, int]]]]): zone name
            and its ``(offset, abbreviation, since)`` rows.
    """
    lines = [
        LICENSE.rstrip("\n") + "\n",
        PREAMBLE,
        "// One name an offset carried: offset in seconds east, the name, "
        "the epoch",
        "// second it took effect.",
        "type Abbreviation = readonly [number, string, number]",
        "",
        "export const TZ_ABBREVS: Readonly<Record<string, "
        "readonly Abbreviation[]>> = {",
    ]
    for name, triples in rows:
        key = name if BARE_KEY.match(name) else f"'{name}'"
        cells = [
            f"[{offset}, '{abbrev}', {since}]"
            for offset, abbrev, since in triples
        ]
        if len(cells) == 1:
            lines.append(f"  {key}: [{cells[0]}],")
        else:
            lines.append(f"  {key}: [")
            lines.extend(f"    {cell}," for cell in cells)
            lines.append("  ],")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    rows = []
    for name in sorted(zoneinfo.available_timezones()):
        if name in SKIPPED:
            continue
        triples = zone_abbreviations(name)
        if triples:
            rows.append((name, triples))
    OUT.write_text(render(rows), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} zones")
    return 0


if __name__ == "__main__":
    sys.exit(main())
